class Country {
  final String name;
  final String flag;

  const Country({required this.name, required this.flag});
}

const List<Country> allCountries = [
  Country(name: "Afghanistan", flag: "🇦🇫"),
  Country(name: "Albania", flag: "🇦🇱"),
  Country(name: "Algeria", flag: "🇩🇿"),
  Country(name: "Andorra", flag: "🇦🇩"),
  Country(name: "Angola", flag: "🇦🇴"),
  Country(name: "Antigua and Barbuda", flag: "🇦🇬"),
  Country(name: "Argentina", flag: "🇦🇷"),
  Country(name: "Armenia", flag: "🇦🇲"),
  Country(name: "Australia", flag: "🇦🇺"),
  Country(name: "Austria", flag: "🇦🇹"),
  Country(name: "Azerbaijan", flag: "🇦🇿"),
  Country(name: "Bahamas", flag: "🇧🇸"),
  Country(name: "Bahrain", flag: "🇧🇭"),
  Country(name: "Bangladesh", flag: "🇧🇩"),
  Country(name: "Barbados", flag: "🇧🇧"),
  Country(name: "Belarus", flag: "🇧🇾"),
  Country(name: "Belgium", flag: "🇧🇪"),
  Country(name: "Belize", flag: "🇧🇿"),
  Country(name: "Benin", flag: "🇧🇯"),
  Country(name: "Bhutan", flag: "🇧🇹"),
  Country(name: "Bolivia", flag: "🇧🇴"),
  Country(name: "Bosnia and Herzegovina", flag: "🇧🇦"),
  Country(name: "Botswana", flag: "🇧🇼"),
  Country(name: "Brazil", flag: "🇧🇷"),
  Country(name: "Brunei", flag: "🇧🇳"),
  Country(name: "Bulgaria", flag: "🇧🇬"),
  Country(name: "Burkina Faso", flag: "🇧🇫"),
  Country(name: "Burundi", flag: "🇧🇮"),
  Country(name: "Cabo Verde", flag: "🇨🇻"),
  Country(name: "Cambodia", flag: "🇰🇭"),
  Country(name: "Cameroon", flag: "🇨🇲"),
  Country(name: "Canada", flag: "🇨🇦"),
  Country(name: "Central African Republic", flag: "🇨🇫"),
  Country(name: "Chad", flag: "🇹🇩"),
  Country(name: "Chile", flag: "🇨🇱"),
  Country(name: "China", flag: "🇨🇳"),
  Country(name: "Colombia", flag: "🇨🇴"),
  Country(name: "Comoros", flag: "🇰🇲"),
  Country(name: "Congo (Congo-Brazzaville)", flag: "🇨🇬"),
  Country(name: "Costa Rica", flag: "🇨🇷"),
  Country(name: "Croatia", flag: "🇭🇷"),
  Country(name: "Cuba", flag: "🇨🇺"),
  Country(name: "Cyprus", flag: "🇨🇾"),
  Country(name: "Czechia (Czech Republic)", flag: "🇨🇿"),
  Country(name: "Denmark", flag: "🇩🇰"),
  Country(name: "Djibouti", flag: "🇩🇯"),
  Country(name: "Dominica", flag: "🇩🇲"),
  Country(name: "Dominican Republic", flag: "🇩🇴"),
  Country(name: "Ecuador", flag: "🇪🇨"),
  Country(name: "Egypt", flag: "🇪🇬"),
  Country(name: "El Salvador", flag: "🇸🇻"),
  Country(name: "Equatorial Guinea", flag: "🇬🇶"),
  Country(name: "Eritrea", flag: "🇪🇷"),
  Country(name: "Estonia", flag: "🇪🇪"),
  Country(name: "Eswatini", flag: "🇸🇿"),
  Country(name: "Ethiopia", flag: "🇪🇹"),
  Country(name: "Fiji", flag: "🇫🇯"),
  Country(name: "Finland", flag: "🇫🇮"),
  Country(name: "France", flag: "🇫🇷"),
  Country(name: "Gabon", flag: "🇬🇦"),
  Country(name: "Gambia", flag: "🇬🇲"),
  Country(name: "Georgia", flag: "🇬🇪"),
  Country(name: "Germany", flag: "🇩🇪"),
  Country(name: "Ghana", flag: "🇬🇭"),
  Country(name: "Greece", flag: "🇬🇷"),
  Country(name: "Grenada", flag: "🇬🇩"),
  Country(name: "Guatemala", flag: "🇬🇹"),
  Country(name: "Guinea", flag: "🇬🇳"),
  Country(name: "Guinea-Bissau", flag: "🇬🇼"),
  Country(name: "Guyana", flag: "🇬🇾"),
  Country(name: "Haiti", flag: "🇭🇹"),
  Country(name: "Holy See", flag: "🇻🇦"),
  Country(name: "Honduras", flag: "🇭🇳"),
  Country(name: "Hungary", flag: "🇭🇺"),
  Country(name: "Iceland", flag: "🇮🇸"),
  Country(name: "India", flag: "🇮🇳"),
  Country(name: "Indonesia", flag: "🇮🇩"),
  Country(name: "Iran", flag: "🇮🇷"),
  Country(name: "Iraq", flag: "🇮🇶"),
  Country(name: "Ireland", flag: "🇮🇪"),
  Country(name: "Israel", flag: "🇮🇱"),
  Country(name: "Italy", flag: "🇮🇹"),
  Country(name: "Jamaica", flag: "🇯🇲"),
  Country(name: "Japan", flag: "🇯🇵"),
  Country(name: "Jordan", flag: "🇯🇴"),
  Country(name: "Kazakhstan", flag: "🇰🇿"),
  Country(name: "Kenya", flag: "🇰🇪"),
  Country(name: "Kiribati", flag: "🇰🇮"),
  Country(name: "Kuwait", flag: "🇰🇼"),
  Country(name: "Kyrgyzstan", flag: "🇰🇬"),
  Country(name: "Laos", flag: "🇱🇦"),
  Country(name: "Latvia", flag: "🇱🇻"),
  Country(name: "Lebanon", flag: "🇱🇧"),
  Country(name: "Lesotho", flag: "🇱🇸"),
  Country(name: "Liberia", flag: "🇱🇷"),
  Country(name: "Libya", flag: "🇱🇾"),
  Country(name: "Liechtenstein", flag: "🇱🇮"),
  Country(name: "Lithuania", flag: "🇱🇹"),
  Country(name: "Luxembourg", flag: "🇱🇺"),
  Country(name: "Madagascar", flag: "🇲🇬"),
  Country(name: "Malawi", flag: "🇲🇼"),
  Country(name: "Malaysia", flag: "🇲🇾"),
  Country(name: "Maldives", flag: "🇲🇻"),
  Country(name: "Mali", flag: "🇲🇱"),
  Country(name: "Malta", flag: "🇲🇹"),
  Country(name: "Marshall Islands", flag: "🇲🇭"),
  Country(name: "Mauritania", flag: "🇲🇷"),
  Country(name: "Mauritius", flag: "🇲🇺"),
  Country(name: "Mexico", flag: "🇲🇽"),
  Country(name: "Micronesia", flag: "🇫🇲"),
  Country(name: "Moldova", flag: "🇲🇩"),
  Country(name: "Monaco", flag: "🇲🇨"),
  Country(name: "Mongolia", flag: "🇲🇳"),
  Country(name: "Montenegro", flag: "🇲🇪"),
  Country(name: "Morocco", flag: "🇲🇦"),
  Country(name: "Mozambique", flag: "🇲🇿"),
  Country(name: "Myanmar (formerly Burma)", flag: "🇲🇲"),
  Country(name: "Namibia", flag: "🇳🇦"),
  Country(name: "Nauru", flag: "🇳🇷"),
  Country(name: "Nepal", flag: "🇳🇵"),
  Country(name: "Netherlands", flag: "🇳🇱"),
  Country(name: "New Zealand", flag: "🇳🇿"),
  Country(name: "Nicaragua", flag: "🇳🇮"),
  Country(name: "Niger", flag: "🇳🇪"),
  Country(name: "Nigeria", flag: "🇳🇬"),
  Country(name: "North Korea", flag: "🇰🇵"),
  Country(name: "North Macedonia", flag: "🇲🇰"),
  Country(name: "Norway", flag: "🇳🇴"),
  Country(name: "Oman", flag: "🇴🇲"),
  Country(name: "Pakistan", flag: "🇵🇰"),
  Country(name: "Palau", flag: "🇵🇼"),
  Country(name: "Palestine State", flag: "🇵🇸"),
  Country(name: "Panama", flag: "🇵🇦"),
  Country(name: "Papua New Guinea", flag: "🇵🇬"),
  Country(name: "Paraguay", flag: "🇵🇾"),
  Country(name: "Peru", flag: "🇵🇪"),
  Country(name: "Philippines", flag: "🇵🇭"),
  Country(name: "Poland", flag: "🇵🇱"),
  Country(name: "Portugal", flag: "🇵🇹"),
  Country(name: "Qatar", flag: "🇶🇦"),
  Country(name: "Romania", flag: "🇷🇴"),
  Country(name: "Russia", flag: "🇷🇺"),
  Country(name: "Rwanda", flag: "🇷🇼"),
  Country(name: "Saint Kitts and Nevis", flag: "🇰🇳"),
  Country(name: "Saint Lucia", flag: "🇱🇨"),
  Country(name: "Saint Vincent and the Grenadines", flag: "🇻🇨"),
  Country(name: "Samoa", flag: "🇼🇸"),
  Country(name: "San Marino", flag: "🇸🇲"),
  Country(name: "Sao Tome and Principe", flag: "🇸🇹"),
  Country(name: "Saudi Arabia", flag: "🇸🇦"),
  Country(name: "Senegal", flag: "🇸🇳"),
  Country(name: "Serbia", flag: "🇷🇸"),
  Country(name: "Seychelles", flag: "🇸🇨"),
  Country(name: "Sierra Leone", flag: "🇸🇱"),
  Country(name: "Singapore", flag: "🇸🇬"),
  Country(name: "Slovakia", flag: "🇸🇰"),
  Country(name: "Slovenia", flag: "🇸🇮"),
  Country(name: "Solomon Islands", flag: "🇸🇧"),
  Country(name: "Somalia", flag: "🇸🇴"),
  Country(name: "South Africa", flag: "🇿🇦"),
  Country(name: "South Korea", flag: "🇰🇷"),
  Country(name: "South Sudan", flag: "🇸🇸"),
  Country(name: "Spain", flag: "🇪🇸"),
  Country(name: "Sri Lanka", flag: "🇱🇰"),
  Country(name: "Sudan", flag: "🇸🇩"),
  Country(name: "Suriname", flag: "🇸🇷"),
  Country(name: "Sweden", flag: "🇸🇪"),
  Country(name: "Switzerland", flag: "🇨🇭"),
  Country(name: "Syria", flag: "🇸🇾"),
  Country(name: "Tajikistan", flag: "🇹🇯"),
  Country(name: "Tanzania", flag: "🇹🇿"),
  Country(name: "Thailand", flag: "🇹🇭"),
  Country(name: "Timor-Leste", flag: "🇹🇱"),
  Country(name: "Togo", flag: "🇹🇬"),
  Country(name: "Tonga", flag: "🇹🇴"),
  Country(name: "Trinidad and Tobago", flag: "🇹🇹"),
  Country(name: "Tunisia", flag: "🇹🇳"),
  Country(name: "Turkey", flag: "🇹🇷"),
  Country(name: "Turkmenistan", flag: "🇹🇲"),
  Country(name: "Tuvalu", flag: "🇹🇻"),
  Country(name: "Uganda", flag: "🇺🇬"),
  Country(name: "Ukraine", flag: "🇺🇦"),
  Country(name: "United Arab Emirates", flag: "🇦🇪"),
  Country(name: "United Kingdom", flag: "🇬🇧"),
  Country(name: "United States of America", flag: "🇺🇸"),
  Country(name: "Uruguay", flag: "🇺🇾"),
  Country(name: "Uzbekistan", flag: "🇺🇿"),
  Country(name: "Vanuatu", flag: "🇻🇺"),
  Country(name: "Venezuela", flag: "🇻🇪"),
  Country(name: "Vietnam", flag: "🇻🇳"),
  Country(name: "Yemen", flag: "🇾🇪"),
  Country(name: "Zambia", flag: "🇿🇲"),
  Country(name: "Zimbabwe", flag: "🇿🇼"),
];
