// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVjTC5iaOS7vW-JKGu_nU_IgBDEvG_XiM',
    appId: '1:319176540267:web:9452aa1ee0662ad7c7b12e',
    messagingSenderId: '319176540267',
    projectId: 'house-rental-ai',
    authDomain: 'house-rental-ai.firebaseapp.com',
    storageBucket: 'house-rental-ai.firebasestorage.app',
    measurementId: 'G-YHCGSGS4E7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgA8YnxkasM7VeqgklOw8RWZgzvsKgCj8',
    appId: '1:319176540267:android:e41557497b3617bfc7b12e',
    messagingSenderId: '319176540267',
    projectId: 'house-rental-ai',
    storageBucket: 'house-rental-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnvwj_kNUqoWNbE3Kc8calKf8z-s2CpC4',
    appId: '1:319176540267:ios:ba1fca2225184913c7b12e',
    messagingSenderId: '319176540267',
    projectId: 'house-rental-ai',
    storageBucket: 'house-rental-ai.firebasestorage.app',
    iosClientId: '319176540267-3acgcg8dsd2767pbds4ti0g52qb5t5g0.apps.googleusercontent.com',
    iosBundleId: 'com.houserental.houseRental',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVjTC5iaOS7vW-JKGu_nU_IgBDEvG_XiM',
    appId: '1:319176540267:web:3e578fe9d68f97fec7b12e',
    messagingSenderId: '319176540267',
    projectId: 'house-rental-ai',
    authDomain: 'house-rental-ai.firebaseapp.com',
    storageBucket: 'house-rental-ai.firebasestorage.app',
    measurementId: 'G-BX214XKFVV',
  );

}